apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nodeapp-depl
  namespace: default
  labels:
    app:  nodeapp-depl
spec:
  selector:
    matchLabels:
      app: nodeapp-depl
  replicas: 3
  template:
    metadata:
      labels:
        app:  nodeapp-depl
    spec:
      containers:
      - name:  nodeapp-depl
        image:  jpatel136/caching
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
        env:
          - name: MONGO_URI
            value: mongodb://mongodb:27017/employeeDB
          - name: REDIS_URL
            value: redis://redis
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: default
spec:
  selector:
    app: nodeapp-depl
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    # nodePort: 30000