apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: default
spec:
  selector:
    app: nodeapp-depl
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    # nodePort: 30000